# Generated by Django 2.1 on 2018-09-02 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_description', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Email_type',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_type', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone_type',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_has_email',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phone_contacts.User')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Email')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Email_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_has_phone',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phone_contacts.User')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Phone')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Phone_type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
