# Generated by Django 2.1 on 2018-09-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='user_has_email',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_has_email',
            name='email_type',
        ),
        migrations.RemoveField(
            model_name='user_has_email',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_has_phone',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_has_phone',
            name='phone_type',
        ),
        migrations.RemoveField(
            model_name='user_has_phone',
            name='user',
        ),
        migrations.CreateModel(
            name='Contact_has_email',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phone_contacts.Contact')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Email')),
                ('email_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Email_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact_has_phone',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phone_contacts.Contact')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Phone')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phone_contacts.Phone_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='User_has_email',
        ),
        migrations.DeleteModel(
            name='User_has_phone',
        ),
    ]
